function requiredGeneratedValue(name: string) {
  const value = process.env[name];
  if (!value)
    throw new Error(`${name} must be generated by the Playwright configuration.`);
  return value;
}

function testEmail(label: string) {
  return `${label}-${requiredGeneratedValue("PERMORA_E2E_RUN_ID")}@example.invalid`;
}

export function e2ePassword() {
  return requiredGeneratedValue("PERMORA_E2E_PASSWORD");
}

export function e2eClientHeaders(lastOctet: number) {
  if (!Number.isInteger(lastOctet) || lastOctet < 1 || lastOctet > 254)
    throw new Error("The E2E client address octet must be between 1 and 254.");
  return { "x-forwarded-for": `192.0.2.${lastOctet}` };
}

export const E2E = {
  approver: {
    id: "e2000000-0000-4000-8000-000000000001",
    email: testEmail("approver"),
  },
  otherApprover: {
    id: "e2000000-0000-4000-8000-000000000002",
    email: testEmail("other-approver"),
  },
  administrator: {
    id: "e2000000-0000-4000-8000-000000000003",
    email: testEmail("administrator"),
  },
  activationAdministrator: {
    id: "e2000000-0000-4000-8000-000000000006",
    email: testEmail("activation-administrator"),
  },
  assignmentRequester: {
    id: "e2000000-0000-4000-8000-000000000007",
    email: testEmail("assignment-requester"),
  },
  requester: {
    id: "e2000000-0000-4000-8000-000000000004",
    email: testEmail("requester"),
  },
  workflowRequester: {
    id: "e2000000-0000-4000-8000-000000000005",
    email: testEmail("workflow-requester"),
  },
  requests: {
    approve: "e2000000-0000-4000-8000-000000000101",
    retry: "e2000000-0000-4000-8000-000000000102",
    stale: "e2000000-0000-4000-8000-000000000103",
    anotherApprover: "e2000000-0000-4000-8000-000000000104",
    unassigned: "e2000000-0000-4000-8000-000000000105",
    assignment: "e2000000-0000-4000-8000-000000000108",
    notificationApproved: "e2000000-0000-4000-8000-000000000106",
    notificationDenied: "e2000000-0000-4000-8000-000000000107",
  },
  notifications: {
    approved: "e2000000-0000-4000-8000-000000000301",
    denied: "e2000000-0000-4000-8000-000000000302",
    activationFailed: "e2000000-0000-4000-8000-000000000303",
    activationSucceeded: "e2000000-0000-4000-8000-000000000304",
  },
} as const;
