function requiredGeneratedValue(name: string) {
  const value = process.env[name];
  if (!value)
    throw new Error(`${name} must be generated by the Playwright configuration.`);
  return value;
}

function testEmail(label: string) {
  return `${label}-${requiredGeneratedValue("PERMORA_E2E_RUN_ID")}@example.invalid`;
}

export function e2ePassword() {
  return requiredGeneratedValue("PERMORA_E2E_PASSWORD");
}

export const E2E = {
  approver: {
    id: "e2000000-0000-4000-8000-000000000001",
    email: testEmail("approver"),
  },
  otherApprover: {
    id: "e2000000-0000-4000-8000-000000000002",
    email: testEmail("other-approver"),
  },
  administrator: {
    id: "e2000000-0000-4000-8000-000000000003",
    email: testEmail("administrator"),
  },
  requester: {
    id: "e2000000-0000-4000-8000-000000000004",
    email: testEmail("requester"),
  },
  workflowRequester: {
    id: "e2000000-0000-4000-8000-000000000005",
    email: testEmail("workflow-requester"),
  },
  requests: {
    approve: "e2000000-0000-4000-8000-000000000101",
    retry: "e2000000-0000-4000-8000-000000000102",
    stale: "e2000000-0000-4000-8000-000000000103",
    anotherApprover: "e2000000-0000-4000-8000-000000000104",
    unassigned: "e2000000-0000-4000-8000-000000000105",
  },
} as const;
