"use client";
import { useState } from "react";
import Link from "next/link";
import { useDemo } from "./demo-provider";
import { Alert, Badge, Button, Card, Empty, Icon, PageHeading } from "./ui";
import { dateLabel } from "@/lib/model";
export function Notifications() {
  const { state, user, dispatch, setNotice } = useDemo();
  const [filter, setFilter] = useState("All");
  const [error, setError] = useState("");
  if (!user) return null;
  const all = state.notifications
    .filter((n) => n.userId === user.id)
    .sort((a, b) => b.at.localeCompare(a.at));
  const shown = all.filter(
    (n) =>
      filter === "All" ||
      (filter === "Unread" && !n.read) ||
      (filter === "Requests" && n.kind === "request") ||
      (filter === "System" && n.kind === "system"),
  );
  function read(ids: string[]) {
    try {
      dispatch({ type: "read", ids });
      setNotice("Notifications marked as read.");
    } catch (e) {
      setError((e as Error).message);
    }
  }
  return (
    <>
      <PageHeading
        title="Notifications"
        description="The latest on your requests, access, and workspace."
        action={
          <Button
            variant="outline"
            disabled={!all.some((n) => !n.read)}
            onClick={() => read(all.map((n) => n.id))}
          >
            Mark all as read
          </Button>
        }
      />
      {error && (
        <Alert title="Could not update notifications" tone="danger">
          {error}
        </Alert>
      )}
      <div className="tabs" aria-label="Notification filters">
        {["All", "Unread", "Requests", "System"].map((label) => (
          <Button
            key={label}
            variant={filter === label ? "secondary" : "outline"}
            aria-pressed={filter === label}
            onClick={() => setFilter(label)}
          >
            {label}
            {label === "Unread" && (
              <span className="tab-count">
                {all.filter((n) => !n.read).length}
              </span>
            )}
          </Button>
        ))}
      </div>
      <Card>
        {shown.length ? (
          <ul className="notification-list">
            {shown.map((n) => (
              <li key={n.id} className={n.read ? "" : "unread"}>
                <span className={`icon-tile tone-${n.tone}`}>
                  <Icon
                    name={
                      n.tone === "success"
                        ? "check"
                        : n.tone === "warning"
                          ? "expire"
                          : n.tone === "danger"
                            ? "key"
                            : "bell"
                    }
                  />
                </span>
                <div className="notification-content">
                  <div className="spread">
                    <h2>{n.title}</h2>
                    <span className="small muted">{dateLabel(n.at)}</span>
                  </div>
                  <p>{n.message}</p>
                  <div className="row wrap">
                    {n.requestId && (
                      <Link
                        className="text-link"
                        href={`/requests/${n.requestId}`}
                      >
                        View request →
                      </Link>
                    )}
                    {!n.read && (
                      <button
                        className="text-button"
                        onClick={() => read([n.id])}
                      >
                        Mark as read<span className="sr-only">: {n.title}</span>
                      </button>
                    )}
                  </div>
                </div>
                {!n.read && <Badge label="Unread" tone="warning" />}
              </li>
            ))}
          </ul>
        ) : (
          <Empty
            title={
              filter === "Unread"
                ? "You’re all caught up"
                : "No notifications here"
            }
            description="Updates from your demo workflow will appear here."
          />
        )}
      </Card>
      <Alert title="In-app updates only" tone="warning">
        Notifications are generated by actions in this demo. No emails or push
        notifications are sent.
      </Alert>
    </>
  );
}
